<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('products')->truncate();
        DB::table('products')->insert([
            [
                'id'=>1,
                'name'=>'Rau Cải Ngọt',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>23100,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin K, Vitamin C, Vitamin B,...',
                'nutrient'=>'Lipit, Protein, Cacbohidrat, Photpho, Canxi, Caroten,...',
                'thumbnail'=>'https://sachico101.com/cdn/images/cach-gieo-rau-cai-ngot-1.jpg',
                'description'=>'Chứa nhiều thành phần dinh dưỡng như: chất xơ, protein, vitamin B1 cùng các loại khoáng chất,... giúp hạ cholesterol,nguy cơ ung thư và ngủ ngon hơn .Ngoài ra còn tốt cho xương,cải thiện bệnh tiểu đường và hỗ trợ tiêu hoá. Với loại rau này, bạn có thể chế biến những món ăn đơn giản như: cải ngọt xào tỏi, xào bò, nấu canh hoặc đơn giản là luộc lên, chấm với nước mắm chua ngọt đều rất ngon và vô cùng tốt cho sức khoẻ.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>2,
                'name'=>'Rau Mồng Tơi',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>28200,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin A, Vitamin C, Vitamin PP, Vitamin B1, Vitamin B2, Vitamin B9,...',
                'nutrient'=>'Calorie, Carbohydrate, Chất béo, Folate, Niacin, Riboflavin, Thiamin,...',
                'thumbnail'=>'https://www.thuocdantoc.org/wp-content/uploads/2019/10/cay-mong-toi.jpg',
                'description'=>'Những giá trị dinh dưỡng nổi bật có thể kể đến của rau mồng tơi là có hàm lượng vitamin A cao, giàu vitamin C hơn cả rau bó xôi và giàu chất sắt giúp cơ thể sản sinh các tế bào hồng cầu khỏe mạnh. Theo Đông y, rau mồng tơi có tính hàn, vị chua, tán nhiệt, mất máu, lợi tiểu, giải độc, đẹp da… Lá và đọt thân non của mồng tơi thường được dùng để nấu canh ăn mát và có tính nhuận trường. Nước ép từ quả dùng trị đau mắt. Có thể dùng rau mồng tơi giã nát đắp chữa vú sưng, nứt, giải độc.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>3,
                'name'=>'Su Su',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>16400,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin B, Vitamin C, Vitamin K,...',
                'nutrient'=>'Protein, Carbohydrate, Chất béo, Chất đạm,...',
                'thumbnail'=>'http://media.cooky.vn/images/blog-2016/cach-trong-su-su-cho-nhieu-ngon-sai-qua-trong-vuon-nha-1.jpg',
                'description'=>'Chứa nhiều chất dinh dưỡng, nhất là vitamin, chất xơ và khoáng chất nhưng lại chứa ít calo, chất béo và hàm lượng carbs giúp cải thiện sức khoẻ tim mạch,kiểm soát đường máu,tốt cho phụ nữ mang thai,chống ung thư và làm chậm quá trình lão hoá. Khi ăn tươi, su su có thể chế biến các món sinh tố hoặc salad. Ngoài ra, su su cũng dễ dàng được hấp, nướng hoặc chiên. Thêm nó vào súp, món hầm và thịt hầm để tăng thêm dinh dưỡng cho món ăn.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>4,
                'name'=>'Bí Đỏ',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>11900,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin B6, Vitamin A, Vitamin C,...',
                'nutrient'=>'Calo, Carbs, Protein, Kali, Chất xơ,...',
                'thumbnail'=>'https://photo-cms-baonghean.zadn.vn/cw607/Uploaded/2021/esfjgtysmyl/2018_05_18/bna_bi_do_anh_minh_thai1362426_1852018.jpg',
                'description'=>'Bí đỏ rất giàu vitamin, khoáng chất và chất chống oxy hóa, tốt cho sức khỏe. Hơn nữa, hàm lượng calo thấp nên rất tốt cho việc giảm cân. Các chất dinh dưỡng và chất chống oxy hóa của nó giúp tăng cường hệ thống miễn dịch, bảo vệ thị lực, giảm nguy cơ mắc một số bệnh ung thư và tăng cường sức khỏe của tim và da. Bí đỏ có hương vị ngọt ngào nên được dùng để chế biến thành nhiều món ăn ngon, từ món canh súp, bánh bí đỏ cho đến món chè.Ngoài ra, cũng có thể chế biến ra sữa bí đỏ để thưởng thức, vừa dinh dưỡng lại vừa phù hợp cho nhiều đối tượng sử dụng, nhất là người lớn tuổi và trẻ nhỏ. Hoặc có thể lấy hạt bí rang lên để ăn như các loại hạt khác tốt cho sức khỏe.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'id'=>5,
                'name'=>'Khoai Tây',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>25000,
                'weight'=>'1 kg',
                'category'=>2,
                'vitamin'=>'Vitamin B6, Vitamin C',
                'nutrient'=>'Protein, Calo, Carbs, Đường, Chất xơ, Chất béo',
                'thumbnail'=>'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3MiXw3O1ABSBRYuDZy4WNK91G6OPUETxd1g&usqp=CAU',
                'description'=>'Khoai tây cũng là nguồn cung cấp nhiều vitamin và các khoáng chất quan trọng đối với cơ thể, đặc biệt là kali và vitamin C. Kali: là loại khoáng chất chiếm ưu thế trong khoai tây, thường tập trung ở phần vỏ và rất có lợi cho sức khỏe tim mạch. Khoai tây có thể được chế biến dưới nhiều hình thức khác nhau, bao gồm luộc, chiên, nướng và có thể sử dụng làm món ăn nhẹ.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>6,
                'name'=>'Măng',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>28200,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin A, Vitamin C, Vitamin B1, Vitamin B2,...',
                'nutrient'=>'Canxi , Magnesium, Mangan, Kali, Sodium,...',
                'thumbnail'=>'https://media.phunutoday.vn/files/van.anh/2017/02/13/mang-tuoi-phunutodayvn-1231.jpg',
                'description'=>'Chứa nhiều thành phần dinh dưỡng cũng như nguyên tố vi lượng cần thiết cho cơ thể như sắt, phốt pho, canxi, protein thực vật. Đặc biệt, măng tươi có hàm lượng chất xơ cao, rất tốt cho hệ tiêu hóa, lại có thể phòng chống táo bón, rất thích hợp với người muốn giảm béo. Thường được nấu chung với các món thịt, được xào, hoặc nấu canh.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>7,
                'name'=>'Bắp Cải',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>25000,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin K, Vitamin B6, Vitamin A,...',
                'nutrient'=>'Calo, Chất đạm, Carb, Chất xơ,...',
                'thumbnail'=>'https://tinicart.vn/wp-content/uploads/2021/03/b%E1%BA%AFp-c%E1%BA%A3i..jpg',
                'description'=>'Cải bắp có hơn 36 loại anthocyanin khác nhau, là thực phẩm ưu tiên cho người mắc bệnh tim mạch và tăng cường sức khỏe tim mạch. Bắp cải có thể được dùng để chế biến các món ăn như súp bắp cải, bắp cải hầm hoặc salad bắp cải.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>8,
                'name'=>'Rau Muống',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>33900,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin C, Vitamin B1, Vitamin B2,...',
                'nutrient'=>'Calorie, Carbohydrate, Protein, Chất béo,...',
                'thumbnail'=>'https://cdn.chotot.com/87W0lc-xHM-BMmUcNetHvmz8OmvaAtTdfxSVcKXb3v4/preset:view/plain/a88ddab6ac699632f58a52cc5d98c4a6-2733444193798234268.jpg',
                'description'=>'Gồm có vitamin A, B, C, canxi, phospho, các chất dinh dưỡng và đặc biệt là hàm lượng chất sắt dồi dào. Ăn rau muống một cách hợp lý sẽ có rất nhiều công dụng như: Thanh nhiệt giải độc, phòng chống tiểu đường, phòng chống các bệnh tim mạch... Có thể được dùng để chế biến các món ăn như luộc, xào. Nước của rau muống có thể dùng để làm súp.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>9,
                'name'=>'Khoai Lang',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>28500,
                'weight'=>'1 kg',
                'category'=>2,
                'vitamin'=>'Vitamin A, Vitamin B9, Vitamin C,...',
                'nutrient'=>'Canxi, Chất xơ, Chất béo, Folate, Magie, Mangan,...',
                'thumbnail'=>'http://baobinhdinh.com.vn/media/5/5/166237/149602.jpg',
                'description'=>'Cung cấp các chất dinh dưỡng tuyệt vời như chất xơ, vitamin và khoáng chất giúp thúc đẩy sức khỏe đường ruột, hỗ trợ thị lực khỏe mạnh, tăng cường chức năng não và hỗ trợ hệ thống miễn dịch. Có thể dùng khoai lang để tạo các món ăn như luộc, hấp, chiên,…',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>10,
                'name'=>'Rau Mùi',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>42900,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin C, Vitamin E, Vitamin A,...',
                'nutrient'=>'Canxi, Chất xơ, Chất béo, Sắt, Phot pho,...',
                'thumbnail'=>'https://cdn.tgdd.vn/2021/01/CookProduct/Cilando-rau-mui-la-gi-cong-dung-va-cach-phan-biet-voi-rau-mui-tay-1-1200x676.jpg',
                'description'=>'Rau mùi rất giàu chất dinh dưỡng gồm protid, lipid, vitamin và nhiều khoáng chất vi lượng giúp hạ đường huyết,tăng cường đề kháng và miễn dịch,tăng cường trí nhớ, não bộ... Dùng để nêm và trang trí trên các món ăn cho đẹp vì màu xanh tươi và mùi thơm của lá, rau mùi còn là một vị thuốc.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>11,
                'name'=>'Dưa Chuột',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>38300,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin A, Vitamin B, Vitamin C,...',
                'nutrient'=>'Năng lượng, Đạm, Tinh bột, Canxi, Kali,...',
                'thumbnail'=>'https://vcdn-vnexpress.vnecdn.net/2020/07/02/dua-chuot-7569-1593684163.jpg',
                'description'=>'Dưa chuột chứa những chất chống ô xi hóa đặc biệt với tỷ lệ hợp lý như β-carotene và α-carotene, vitamin C, vitamin-A, zea-xanthin và lutein giúp hỗ trợ tim mạch, bổ sung kali, phục hồi thị giác và ngăn ngừa ung thư... Được sử dụng trong bữa ăn của các gia đình như một loại rau ăn mát và giòn. ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>12,
                'name'=>'Bí Đao',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>20300,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin B1, Vitamin B2,...',
                'nutrient'=>'Năng lượng, Đạm, Chất béo, Chất xơ, Canxi,...',
                'thumbnail'=>'https://nongnghiepthongminh.vn/upload/images/nhung/b%C3%AD%20%C4%91ao%20xanh/v_dsft_grande.jpg',
                'description'=>'Bí đao rất giàu chất dinh dưỡng gồm glucid, protid, canxi, photpho.Bên cạnh đó, bí đao còn chứa hàm lượng dầu thực vật cao, rất có lợi cho da và tóc. Bí đao thường dùng nấu súp, hấp, xào. Bí đao còn được dùng thắng với đường làm mứt bí.Lá và ngọn bí đao cũng có thể dùng như rau.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>13,
                'name'=>'Rau Cải Thìa',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>39400,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin C, Vitamin K, Vitamin A,...',
                'nutrient'=>'Calo, Protein, Carbohydrate,...',
                'thumbnail'=>'https://acfarmvn.com/wp-content/uploads/2019/01/cai-thia.jpg',
                'description'=>'Cải thìa rất giàu vitamin C giúp chống oxy hóa mạnh mẽ giúp ngăn ngừa những hư tổn trên da do tia tử ngoại, không khí ô nhiễm và khói thuốc gây ra. Với loại rau này, bạn có thể chế biến những món ăn đơn giản như: cải ngọt xào tỏi, xào bò, nấu canh hoặc đơn giản là luộc lên, chấm với nước mắm chua ngọt đều rất ngon và vô cùng tốt cho sức khoẻ.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>14,
                'name'=>'Cam',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>43900,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin B,...',
                'nutrient'=>'Calo, Protein, Carbohydrate, Đường,...',
                'thumbnail'=>'https://vnn-imgs-f.vgcloud.vn/2021/07/21/10/cam-sanh-1.jpg',
                'description'=>'Cung cấp cho cơ thể vitamin C, vitamin A, can-xi, chất sắt... giúp cơ thể tăng cường hệ miễn dịch, hỗ trợ tiêu hóa, tăng cường thể lực và chống ung thư... Có thể ăn hoặc làm nước ép, hoặc cũng có thể thêm cam vào món salad hoặc bột yến mạch.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>15,
                'name'=>'Chuối',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>19500,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin B6,...',
                'nutrient'=>'Calo, Protein, Carbs, Đường, Chất xơ,...',
                'thumbnail'=>'http://c.files.bbci.co.uk/18443/production/_113359399_gettyimages-1159176981.jpg',
                'description'=>'Chuối chứa nhiều kali, vitamin B6, vitamin C giúp giảm huyết áp ở những người có mức huyết áp tăng cao và có lợi cho sức khỏe của tim. Có thể ăn trực tiếp, hoặc cũng có thể cắt mỏng, sau đó đem chiên hay nướng để ăn giống như khoai tây.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>16,
                'name'=>'Khế',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>62500,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin A,...',
                'nutrient'=>'Chất xơ, Protein,...',
                'thumbnail'=>'https://quangon.vn/resources/2021/01/20/loi-ich-suc-khoe-cua-khe-2.jpg',
                'description'=>'Ít calo nhưng giàu chất xơ nên đặc biệt tốt cho sức khỏe. Không những vậy, loại quả này cũng chứa ít chất béo nhưng chứa nhiều vitamin B, vitamin C, natri, kali, sắt và một số chất chống oxy hóa quan trọng, cần thiết cho cơ thể. Có thể ăn trực tiếp hoặc sử dụng vào các món ăn.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>17,
                'name'=>'Đào',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>35000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C,...',
                'nutrient'=>'Protein, Chất xơ, Canxi, Phot pho,...',
                'thumbnail'=>'https://cdn.tgdd.vn/Files/2020/06/13/1262832/hoc-cach-phan-biet-cac-loai-dao-tuoi-dang-ban-tren-thi-truong-202006202149081661.jpg',
                'description'=>'Giàu vitamin A, beta-carotene và vitamin C, vitamin E giúp giảm lượng kali máu, ung thư, béo phì, cholesterol, ứ máu và các bệnh thoái hóa thần kinh… Có thể ăn trực tiếp hoặc sử dụng để pha nước uống.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>18,
                'name'=>'Tỏi',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>32000,
                'weight'=>'1 kg',
                'category'=>2,
                'vitamin'=>'Vitamin B1, Vitamin B2, Vitamin B3, Vitamin B6,...',
                'nutrient'=>'Calo , Natri, Kali, Carbohydrate,...',
                'thumbnail'=>'https://nld.mediacdn.vn/2014/suckhoe-1417874905411.jpg',
                'description'=>'Tỏi rất giàu chất dinh dưỡng như protein, carbohydrates, calo và các dưỡng chất như vitamin nhóm B (B1, B2, B3, B6), sắt, canxi, kali, mangan, magie, photpho,... giúp cải thiện huyết áp cao, giảm cholesterol và nguy cơ mắc bệnh tim, cung cấp chất chống oxy hóa và cải thiện sức khỏe xương... Tỏi có thể sử dụng thành gia vị trong nước chấm pha chế.Hoặc tỏi được trộn đều với các món rau xào khiến món ăn thêm mùi thơm',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>19,
                'name'=>'Me',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>53900,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin A,...',
                'nutrient'=>'Magiê , Canxi, Kali, Phot pho,...',
                'thumbnail'=>'https://caythuoc.org/wp-content/uploads/2019/06/Cay-me-1024x681.jpg   ',
                'description'=>'Ăn me có thể bổ sung lượng vitamin C mà cơ thể bạn cần mỗi ngày giúp duy trì răng lợi của bạn được chắc khỏe. Ngoài việc có chứa thiamin, me cũng là nguồn cung cấp dồi dào niacin hữu ích trong việc giảm cholesterol xấu trong cơ thể và làm tăng mức cholesterol tốt. Me ngọt là một loại quả có vị chua ngọt. Cùi me được sử dụng rộng rãi để nấu ăn, nó được sử dụng trong nước sốt, nước xốt, tương ớt, đồ uống và món tráng miệng.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>20,
                'name'=>'Bưởi',
                'gardenName'=>'Vườn rau, trái cây sạch bà Họa',
                'price'=>60000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin B2, Vitamin P,...',
                'nutrient'=>'Calo , Carb, Chất đạm, Chất xơ,...',
                'thumbnail'=>'http://tapchiyhoccotruyen.vn/wp-content/uploads/2021/08/cong-dung-cua-buoi-mot-so-mon-an-ngon-tu-loai-qua-14.jpg',
                'description'=>'Bưởi cung cấp vitamin C giúp tránh được cảm lạnh, sốt, nhiễm trùng và các chứng bệnh khác.Với hàm lượng chất xơ cao, bưởi rất tuyệt vời đối với nhu động ruột. Có thể ăn trực tiếp hoặc ép thành nước uống.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>21,
                'name'=>'Atiso',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>80000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin K,...',
                'nutrient'=>'Calo , Carbohydrate, Protein, Chất xơ,...',
                'thumbnail'=>'https://dacsandalat.com.vn/wp-content/uploads/2016/03/91777238_667527247368302_6411045206828777472_n.jpg',
                'description'=>'Atisô rất giàu vitamin và chất chống oxy hóa lành mạnh. Các chất chống oxy hóa như carotenoids, tocopherols, flavonoid… cùng với vitamin (A, C, D và E) giúp tăng cường vẻ đẹp cho làn da. Vitamin C giúp khắc phục các vấn đề về da và sắc tố. Vitamin A bảo vệ chống lại tia UV, da chảy xệ và nếp nhăn.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>22,
                'name'=>'Cần Tây',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>35000,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin C, Vitamin K, Vitamin B,...',
                'nutrient'=>'Kali , Folate, Choline,...',
                'thumbnail'=>'https://tinicart.vn/wp-content/uploads/2021/07/rau-c%E1%BA%A7n-t%C3%A2y.jpg',
                'description'=>'Nhờ chứa nhiều chất xơ nên cần tây có khả năng chữa chứng rối loạn tiêu hoá và giúp ngăn ngừa táo bón hiệu quả. Ăn cần tây có thể giúp bạn điều trị rối loạn giấc ngủ hoặc mất ngủ hiệu quả. Hàm lượng magie cũng như tinh dầu trong rau có tác dụng làm dịu thần kinh. Nhờ đó, bạn có thể thư giãn và ngủ ngon giấc.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>23,
                'name'=>'Thì Là',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>80000,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin C, Vitamin A,...',
                'nutrient'=>'Folate , Mangan, Calo,...',
                'thumbnail'=>'https://storage.googleapis.com/ifarmer-vn/4d8c4111e4ba4454ab733826ed8bd38f/rau-thi-la.jpg',
                'description'=>'Thì là rất giàu chất chống oxy hóa giúp bảo vệ cơ thể khỏi tác hại từ các gốc tự do. Trong loại rau này cũng chứa nhiều hợp chất kháng khuẩn có khả năng chống viêm hiệu quả. Một số chất dinh dưỡng thiết yếu khác được tìm thấy trong thì là bao gồm vitamin C, kali, mangan, canxi, sắt và một lượng nhỏ vitamin B.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>24,
                'name'=>'Nấm',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>130000,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin D2, Vitamin D,...',
                'nutrient'=>'Protein , Chất xơ, Kali,...',
                'thumbnail'=>'https://cookbeo.com/media/2021/05/cac-loai-nam/thumbnails/nam-bao-ngu.jpg',
                'description'=>'Nấm cung cấp chất béo, cholesterol có lợi, gluten, chất xơ và khi ăn nấm, bạn nạp rất ít lượng calo và natri cho cơ thể. Bên cạnh đó, nấm là một nguồn tuyệt vời cho vitamin nhóm B, các enzyme quan trọngprotein, các chất hữu cơ và khoáng chất như đồng, kẽm, kalivà hầu như là nguồn duy nhất cho vitamin D tự nhiên.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>25,
                'name'=>'Ớt Chuông',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>61000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin A, Vitamin E,...',
                'nutrient'=>'Chất béo , Protein, Canxi,...',
                'thumbnail'=>'https://cdn.tgdd.vn/2021/08/content/Ot-chuong-co-tac-dung-gi-nhung-tac-dung-cua-ot-chuong-doi-voi-suc-khoe-1-730x488.jpg',
                'description'=>'Thành phần dinh dưỡng trong ớt chuông với hàm lượng vitamin B6 và khoáng chất magie trong ớt đỏ giúp giảm chứng lo âu, đặc biệt những triệu chứng liên quan đến thời kỳ tiền mãn kinh. Vitamin B6 còn giúp giảm đầy hơi ngăn ngừa huyết áp cao đồng thời còn có tác dụng thuốc lợi tiểu tự nhiên.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>26,
                'name'=>'Ớt Cay',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>80000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin B,...',
                'nutrient'=>'Calo, Protein, Carb,...',
                'thumbnail'=>'https://caythuoc.org/wp-content/uploads/2019/07/Cay-ot-1024x768.jpg',
                'description'=>'Ớt có một số đặc tính chữa bệnh, nó có thể giúp “đổ mồ hôi ngoài, long đờm, khử ẩm”. Theo giải thích của y học hiện đại, ớt có thể thúc đẩy lưu thông máu, cải thiện tê cóng, lạnh, đau đầu… Các chị em có thể rất bất ngờ khi biết rằng ớt có thể làm đẹp da. Ớt có thể thúc đẩy sự tiết hormone, cải thiện tình trạng da.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>27,
                'name'=>'Cải Xoong',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>40000,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin C, Vitamin A,...',
                'nutrient'=>'Calo, Protein, Carb, Chất béo,...',
                'thumbnail'=>'https://khuyennongtphcm.com/wp-content/uploads/2020/09/cai-xoong.jpg',
                'description'=>'Cải xoong là một loại rau tốt cho cơ thể. Trước hết, nó có tác dụng khai vị, bổ, kích thích tiêu hóa, cung cấp chất khoáng cho cơ thể, chống thiếu máu , chống bệnh hoại huyết, lọc máu, lợi tiểu, giảm đường huyết, trị ho. Nó còn làm ra mồ hôi, trị giun và giải độc nicotin.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>28,
                'name'=>'Khoai Mỡ',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>47000,
                'weight'=>'1 kg',
                'category'=>2,
                'vitamin'=>'Vitamin C, Vitamin A,...',
                'nutrient'=>'Carbohydrate, Protein, Chất xơ, Chất béo,...',
                'thumbnail'=>'https://lamtho.vn/resources/2020/08/01/cach-trong-khoai-mo-8.jpg',
                'description'=>'Có tác dụng giảm đau cơ bắp, đau bụng, đau hệ thần kinh. Khoai mỡ còn có thành phần chống viêm nhiễm cho nhóm người mắc bệnh viêm khớp dạng thấp tác dụng giảm sốt, tăng cường chức năng cho bàng quang, gan và tác dụng giảm mỡ máu.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>29,
                'name'=>'Sắn',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>20000,
                'weight'=>'1 kg',
                'category'=>2,
                'vitamin'=>'Vitamin C, Vitamin B1,...',
                'nutrient'=>'Đường, Chất đạm, Chất xơ, Chất béo,...',
                'thumbnail'=>'https://vinmec-prod.s3.amazonaws.com/images/20210102_034242_679147_san.max-800x800.jpg',
                'description'=>'Sắn là rất giàu calo, chứa nhiều carbohydrate, các vitamin và khoáng chất quan trọng. Đây là nguồn cung cấp vitamin C, vitamin B1, vitamin B2 và vitamin B3 tốt. Sắn là một thực phẩm có chỉ số đường huyết (GI) thấp, giúp kiểm soát lượng đường, mức độ chất béo trung tính và các chất béo khác nhau trong máu.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>30,
                'name'=>'Bạc Hà',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>10000,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin C, Vitamin A,...',
                'nutrient'=>'Carbohydrate, Chất đạm, Chất xơ, Chất béo,...',
                'thumbnail'=>'https://file.hstatic.net/200000135315/article/cong-dung-bot-bac-ha__4__5a72735187aa45629c62ca44aef3391f_d86c78819ba942e793048bce336f1af8.jpg',
                'description'=>'Bạc hà có tác dụng làm ra mồ hôi, trừ phong giảm đau, chỉ ho, kiện vị, chỉ tả, tăng tiết mật, kích thích tiêu hóa, giải độc, thúc ban sởi mọc. Dùng bạc hà trị ho, cảm mạo phong nhiệt, biểu hiện sốt cao, mũi tắc, đau đầu, ít hoặc không có mồ hôi.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>31,
                'name'=>'Củ Sen',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>50000,
                'weight'=>'1 kg',
                'category'=>2,
                'vitamin'=>'Vitamin C, Vitamin B2, Vitamin B9,...',
                'nutrient'=>'Protein, Canxi, Chất xơ, Kali,...',
                'thumbnail'=>'https://huongsentraly.vn/wp-content/uploads/2019/11/b7b0e810-9baa-11e8-9362-35ecdb7e4265.jpg',
                'description'=>'Trong củ sen không chứa nhiều calo nhưng lại nhiều vitamin, khoáng chất và chất xơ. Củ sen có tác dụng điều hòa các nhu động ruột rất tốt , hỗ trợ hệ tiêu hóa, giảm cảm giác thèm ăn. Vì vậy mà củ sen rất phù hợp với những người đang ăn kiêng để giảm cân. Bên cạnh đó, củ sen cũng giúp phòng chống béo phì.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>32,
                'name'=>'Nghệ',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>600000,
                'weight'=>'1 kg',
                'category'=>2,
                'vitamin'=>'Vitamin C, Vitamin E, Vitamin K,...',
                'nutrient'=>'Protein, Canxi, Magiê, Kali,...',
                'thumbnail'=>'https://cdn.tgdd.vn/2020/07/content/IMG3351-800x533.jpg',
                'description'=>'Củ nghệ và đặc biệt là hợp chất curcumin có nhiều lợi ích sức khỏe đã được khoa học chứng minh, như khả năng ngăn ngừa bệnh tim, Alzheimer và ung thư. Đây là một chất chống viêm và chống oxy hóa mạnh mẽ và cũng có thể giúp cải thiện các triệu chứng trầm cảm và viêm khớp.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>33,
                'name'=>'Su Hào',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>10000,
                'weight'=>'1 kg',
                'category'=>2,
                'vitamin'=>'Vitamin C, Vitamin B,...',
                'nutrient'=>'Anbumin, Canxi, Chất xơ, Sắt,...',
                'thumbnail'=>'https://npfoodmart.com/wp-content/uploads/2021/06/1d1ad3f8e90ec35308fd1e26d59cc596.jpg',
                'description'=>'Su hào có tính mát, vị ngọt hơi đắng, có tác dụng hóa đờm, giải khát, giải độc, lợi thủy, tiêu viêm, giúp dạ dày. Chủ yếu dùng chữa nước tiểu đục, đi ngoài ra máu, nhọt độc không rõ nguyên nhân, tỳ hư hỏa vượng, trúng phong bất tỉnh.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>34,
                'name'=>'Rau Răm',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>15000,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin C, Vitamin A,...',
                'nutrient'=>'Kali, Canxi, Nước, Sắt,...',
                'thumbnail'=>'https://ttgdtxninhthuan.edu.vn/wp-content/uploads/2021/01/cay-rau-ram-4.jpg',
                'description'=>'Rau răm là vị thuốc có tác dụng chống viêm hạ khí, kích thích tiêu hóa, trừ phong hàn, hoạt huyết tiêu độc. Rau răm được dùng cả lá, cả cây, được dùng riêng hoặc phối hợp cùng những vị khác thành bài. Có thể dùng tươi hoặc phơi khô, giã sống vắt lấy nước uống, bã đắp.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>35,
                'name'=>'Rau Má',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>35000,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin C, Vitamin B1,...',
                'nutrient'=>'Phot pho, Canxi, Sắt,...',
                'thumbnail'=>'https://madefresh.com.vn/wp-content/uploads/2020/06/thong-tin-dinh-duong-rau-ma-scaled.jpg',
                'description'=>'Rau má có tác dụng tiêu nhiệt, dưỡng âm, giải độc,… thường dùng để điều trị nhiều bệnh như viêm họng, viêm amidan, ngộ độc thực phẩm. Ngoài ra, chúng còn được sử dụng với mục đích giảm nhanh các triệu chứng bệnh ngoài da và hỗ trợ cải thiện bệnh tim mạch và thần kinh.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>36,
                'name'=>'Cải Đắng',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>13000,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin B2, Vitamin B1,...',
                'nutrient'=>'Kali, Canxi, Chất xơ,...',
                'thumbnail'=>'https://bachungyduoc.vn/wp-content/uploads/2018/09/cai-dang.jpg',
                'description'=>'Cải đắng có vị cay, tính ôn, có tác dụng thanh nhiệt, giúp tăng cường hệ tiêu hóa, chống lão hóa da và tốt cho tim mạch. Sở dĩ người ta thường sử dụng rau cải đắng chữa gout là do những tác dụng hữu hiệu của nó trong điều trị bệnh.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>37,
                'name'=>'Rong Biển',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>100000,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin A, Vitamin B1,...',
                'nutrient'=>'Carbs, Protein, Chất béo,...',
                'thumbnail'=>'https://madefresh.com.vn/wp-content/uploads/2020/05/Tao-spirulina-la-gi-1024x576.jpg',
                'description'=>'Rong biển khô rất giàu chất bột đường, chất xơ, đạm, sinh tố và chất khoáng',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>38,
                'name'=>'Đậu Đũa',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>40000,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin C, Vitamin B1, Vitamin B2,...',
                'nutrient'=>'Calo, Chất đạm, Chất béo, Chất xơ,...',
                'thumbnail'=>'https://media.ex-cdn.com/EXP/media.yeugiadinh.vn/files/content/2020/05/20/daudua_20200519112329-0823.jpg',
                'description'=>'Đậu đũa cung cấp nguồn chất xơ quan trọng giúp bảo vệ đường tiêu hóa, kích thích nhu động ruột và làm mềm phân ở những bệnh nhân táo bón. Một nghiên cứu khác chỉ ra rằng chất xơ còn có thể giúp ngăn ngừa những rối loạn tiêu hóa khác như: Trào ngược dạ dày,bệnh trĩ vàviêm loét dạ dày...',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>39,
                'name'=>'Củ Hẹ',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>50000,
                'weight'=>'1 kg',
                'category'=>2,
                'vitamin'=>'Vitamin C, Vitamin A,...',
                'nutrient'=>'Calo, Chất đạm, Chất béo, Tinh bột,...',
                'thumbnail'=>'https://i.ytimg.com/vi/IgWv-2h_tXM/maxresdefault.jpg',
                'description'=>'Hẹ có chứa allicin. Allicin có tác dụng giảm huyết áp và ngăn quá trình sản sinh cholesterol trong cơ thể. Hơn nữa, chúng cũng có đặc tính chống vi khuẩn và chống nấm, tẩy vi khuẩn và nấm trong đường ruột, đảm bảo cho hệ thống tiêu hóa hoạt động tốt.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>40,
                'name'=>'Rau Rút',
                'gardenName'=>'Rau sạch Minh Hiệp',
                'price'=>35000,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin B1, Vitamin B2, Vitamin PP,...',
                'nutrient'=>'Năng lượng, Carbs, Chất đạm,...',
                'thumbnail'=>'https://cdn.tgdd.vn/2021/05/content/rau-nhut-rau-rut-la-gi-rau-nhut-co-tac-dung-gi-ai-khong-nen-an-rau-nhut-4-800x600.jpg',
                'description'=>'Rau rút có mùi thơm đặc biệt như mùi nấm hương, thân ăn giòn',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>41,
                'name'=>'Mướp',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>27500,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin B1, Vitamin B3, Vitamin C,...',
                'nutrient'=>'Canxi, Phot pho, Sắt,...',
                'thumbnail'=>'https://ondinhtieuduong.com/wp-content/uploads/2019/09/MUOP-HUONG.jpg',
                'description'=>'Rau rút có vị ngọt, tính hàn, không độc, tác dụng an thần, mát gan, giải nhiệt độc, có tác dụng chữa chứng mất ngủ, trị nóng trong sinh mụn... làm thông huyết mạch, điều hòa tỳ vị, thông thủy đạo, lợi tiểu tiện, tiêu viêm, nhuận tràng, hạ sốt.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>42,
                'name'=>'Củ Riềng',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>15000,
                'weight'=>'1 kg',
                'category'=>2,
                'vitamin'=>'Vitamin C,...',
                'nutrient'=>'Calo, Carbohydrate, Protein, Chất béo,...',
                'thumbnail'=>'https://bhfood.vn/wp-content/uploads/2020/05/gieng-cu.jpg',
                'description'=>'Củ riềng có khả năng loại bỏ chất độc và cải thiện sự tuần hoàn máu. Kết quả là có thêm dưỡng chất cung cấp cho mô da. Những đặc tính chống ô xy hóa của củ riềng giúp ngăn các gốc tự do gây thương tổn cho da, qua đó duy trì độ mềm của da.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>43,
                'name'=>'Mía',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>1000,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin B2,...',
                'nutrient'=>'Calo, Chất xơ, Protein,...',
                'thumbnail'=>'https://mayviendong.vn/wp-content/uploads/2019/11/1_646646.jpg',
                'description'=>'Mía có vô số tác dụng đối với sức khỏe con người như điều trị sỏi thận, chữa bệnh vàng da, chống nhiễm trùng, phòng ngừa ung thư và và được sử dụng để sản xuất đường.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>44,
                'name'=>'Đậu Bắp',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>20000,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin A, Vitamin E, Vitamin B,...',
                'nutrient'=>'Folate, Chất xơ, Calo,...',
                'thumbnail'=>'https://hatgionglamson.com/asset/upload/image/hat-giong-dau-bap.jpg?v=20190410',
                'description'=>'Đậu bắp là loại thực vật chứa rất nhiều chất dinh dưỡng như Protein, Vitamin A,E,B, Axit amin, Kali, Canxi,... có lợi cho cơ thể con người cùng với rất nhiều tác dụng như: Bệnh tiểu đường: đậu bắp chứa các chất như insulin có khả năng hỗ trợ giảm lượng đường trong máu, giúp ích cho quá trình điều trị bệnh tiểu đường.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>45,
                'name'=>'Tía Tô',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>50000,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin C, Vitamin A,...',
                'nutrient'=>'Protein, Chất béo, Carb,...',
                'thumbnail'=>'https://cdn.tgdd.vn/2020/10/CookProduct/Tia-to-duoc-tinh-tac-dung-va-nhung-luu-y-khi-su-dung-0-1200x676.jpg',
                'description'=>'Tía tô là vị thuốc được xếp vào loại kích thích ra mồ hôi, nước sắc và cồn chiết xuất lá tía tô đều có tác dụng giãn mạch ngoài da, hạ sốt, trừ cảm mạo. Hạt chế thành trà uống và thuốc hạ khí, cành làm thuốc an thai.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>46,
                'name'=>'Quất',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>35000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin A,...',
                'nutrient'=>'Calo, Chất đạm, Carb, Chất xơ,...',
                'thumbnail'=>'https://lamtho.vn/resources/2019/12/24/giam-canh-quat-2.jpg',
                'description'=>'Quất cung cấp vitamin C, A, B2, chất xơ, mangan, sắt, magiê và đồng giúp chữa ho do phong hàn và các bệnh đường tiêu hoá: đau dạ dày, nôn mửa, chán ăn.. Điều hòa, cải thiện chức năng gan.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>47,
                'name'=>'Mít',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>30000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin A,...',
                'nutrient'=>'Canxi, Kali, Sắt, Thiamin,...',
                'thumbnail'=>'https://hatgiongnongnghiep.com/wp-content/uploads/2020/06/bf57c2f7ecd6a27a1ee0aed0a7b10381.jpg',
                'description'=>'Mít là loại trái cây có nguồn vitamin C tuyệt vời. Vitamin C là loại chất giúp cơ thể chống hiện tượng nhiễm virus và nhiễm khuẩn',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>48,
                'name'=>'Sầu Riêng',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>65000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin B,...',
                'nutrient'=>'Calo, Chất xơ, Carb, Chất béo, Protein,...',
                'thumbnail'=>'https://sauriengri6.com/wp-content/uploads/2017/10/2-600x400.jpg',
                'description'=>'Mít là nguồn bổ sung vitamin C, vitamin A làm tăng sức đề kháng của cơ thể, chống oxy hoá mạnh mẽ, giúp duy trì đủ độ ẩm giúp da hồng hào và hạn chế nếp nhăn. Mít chỉ làm bạn tăng cân chỉ khi bạn ăn quá nhiều. Nếu ăn với liều lượng hợp lý, mít có thể giúp bạn giảm cân và tốt cho sức khỏe.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>49,
                'name'=>'Chanh Vàng',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>60000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin B1, Vitamin B6,...',
                'nutrient'=>'Kali, Canxi, Magie, Sắt, Kẽm,...',
                'thumbnail'=>'https://c8.alamy.com/compit/s25b8w/i-limoni-in-un-boschetto-di-limone-di-sorrento-italia-s25b8w.jpg',
                'description'=>'Kali trong chanh vàng giúp kiểm soát huyết áp, kích thích não bộ và đảm bảo hoạt động chức năng thần kinh. Bên cạnh đó, vitamin C trong chanh vàng còn có tác dụng tăng sức đề kháng với bệnh cảm cúm. Một chút nước ấm pha vài lát chanh vàng và thêm mật ong sẽ là đồ uống nhanh chóng, giúp bạn hồi phục khi bị cảm.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>50,
                'name'=>'Chanh Xanh',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>15000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C,...',
                'nutrient'=>'Calo, Natri, Kali, Cacbohydrat, Protein,...',
                'thumbnail'=>'https://cayxanhvanphucvien.com/wp-content/uploads/2021/06/cay-chanh-1.jpg',
                'description'=>'Chanh xanh là loại quả tròn, thường có màu xanh tươi, có vị chua và mọng nước. Loại quả này là nguồn vitamin vô cùng mạnh mẽ, đặc biệt chứa hàm lượng lớn vitamin ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>51,
                'name'=>'Mận',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>20000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin A, Vitamin C, Vitamin K, Vitamin B,...',
                'nutrient'=>'Năng lượng, Carbs, Kali, Đồng, Mangan, Phốt pho, Magie,...',
                'thumbnail'=>'https://traicayvuongtron.vn/resources/uploads/kien_thuc_trai_cay/manpunhi/manpunhi.jpg',
                'description'=>'Do rất giàu vitamin C cho nên chanh xanh rất tốt để sử dụng khi bạn bị cảm lạnh thông thường. Nó cũng giúp tăng cường hệ miễn dịch của bạn. Ngoài ra, trái chanh xanh còn được cho rằng có thể có đặc tính kháng virus và sát trùng, tăng cường chức năng gan, giảm các vấn đề không tốt cho hệ tiêu hóa.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>52,
                'name'=>'Anh Đào',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>100000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin A, Vitamin K,...',
                'nutrient'=>'Chất chống ô xy hóa, Chất xơ, Polyphenol và Kali,...',
                'thumbnail'=>'https://cayhoala.com/wp-content/uploads/2020/01/qua-cherry-anh-dao-1.jpg',
                'description'=>'Nước ép anh đào rất giàu vitamin, khoáng chất và các hợp chất thiên nhiên có nguồn gốc thực vật có lợi được chứng minh là giúp tăng cường hệ miễn dịch của bạn. Đặc biệt, các nhà nghiên cứu tin rằng hàm lượng chất chống oxy hóa cao của quả anh đào có thể giúp ngăn ngừa nhiễm trùng.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>53,
                'name'=>'Chôm Chôm',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>40000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin B1, Vitamin B2, Vitamin B3,...',
                'nutrient'=>'Năng lượng, Nước, Carbohydrate, Chất đạm, Chất béo, Chất xơ,...',
                'thumbnail'=>'https://cdn.tgdd.vn/2020/11/CookProduct/An-chom-chom-co-tac-dung-gi-cach-chon-mua-va-bao-quan-qua-chom-chom-1-1200x676.jpg',
                'description'=>'Nhiều hợp chất chứa trong chôm chôm được chứng minh là có tác dụng tăng cường hệ thống miễn dịch cơ thể, từ đó có khả năng giúp bạn chống lại bệnh nhiễm trùng. Chẳng hạn, hàm lượng vitamin C đáng kể thúc đẩy việc sản xuất các tế bào bạch cầu mà cơ thể cần để chống lại sự nhiễm trùng.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>54,
                'name'=>'Dừa',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>40000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin B2, Vitamin B3, Vitamin B1,...',
                'nutrient'=>'Canxi, Sắt, Magiê, Mangan, Kẽm,...',
                'thumbnail'=>'https://bizweb.dktcdn.net/thumb/1024x1024/100/324/966/products/dua-xiem-xanh-lun-island-min.png?v=1625027412830',
                'description'=>'Nước dừa tươi rất giàu kali và các loại khoáng chất khác nên có thể giúp bạn điều tiết chất lỏng bên trong cơ thể, giúp bổ sung và bù nước cho cơ thể. Loại nước này đã được dùng để trị mất nước do bệnh lỵ, bệnh tả, tiêu chảy và rối loạn tiêu hóa.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>55,
                'name'=>'Dưa',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>85000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin A, Vitamin C,...',
                'nutrient'=>'Calo, Chất béo, Natri, Carbohydrate, Chất xơ, Đường, Chất đạm,...',
                'thumbnail'=>'https://hoaquafuji.com/storage/app/media/dua-luoi-bao-nhieu-tien-hien-nay-fuji.jpg',
                'description'=>'Dưa có nhiều chất xơ và nhiều nước nên hỗ trợ tiêu hóa tốt, ngăn ngừa tình trạng táo bón, ợ hơi, khó tiêu ở phụ nữ mang thai. Hàm lượng Kali trong vàng cũng giúp thai phụ cân bằng huyết áp. Với thành phần vitamin A, dưa vàng giúp giảm tình trạng mệt mỏi của phụ nữ mang thai.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>56,
                'name'=>'Nhãn',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>85000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin B1, Vitamin B2,...',
                'nutrient'=>'Calo, Nước, Protein, Carbohydrate, Lipid, Chất xơ, Canxi, Sắt,...',
                'thumbnail'=>'https://traicayvuongtron.vn/resources/uploads/kien_thuc_trai_cay/nhan/hungyen3.jpg',
                'description'=>'Nhãn có tác dụng kích thích lá lách và tim mạch hoạt động hiệu quả, làm trẻ hóa quá trình lưu thông máu, cung cấp hiệu ứng làm dịu hệ thần kinh, giảm căng thẳng, mệt mỏi. Chúng cũng giúp điều trị chứng suy nhược thần kinh, mất ngủ và trầm cảm.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>57,
                'name'=>'Quýt',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>27000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin A,...',
                'nutrient'=>'Kali, Canxi,...',
                'thumbnail'=>'https://cdn.tgdd.vn/2021/04/content/q3-800x500.jpg',
                'description'=>'Quýt giúp ngăn ngừa đau đầu, trợ tiêu hóa và tốt cho việc giảm viêm. Loại quả này cũng giúp ngăn ngừa chứng chuột rút nhờ hàm lượng kali cao. Quýt không phải là một nguồn rất lớn canxi, nhưng nó chứa 22 mg mỗi khẩu phần. Canxi là một khoáng chất cần thiết giúp làm dịu thần kinh và làm giảm huyết áp của bạn.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>58,
                'name'=>'Dâu Tây',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>100000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin B9,...',
                'nutrient'=>'Năng lượng, Nước, Protein, Carbs, Đường, Chất xơ, Chất béo,...',
                'thumbnail'=>'https://cdn.tgdd.vn/2020/10/CookProduct/1-1200x676-37.jpg',
                'description'=>'Dâu tây có chứa hàm lượng cao vitamin, chất xơ và các chất chống oxy hóa đặc biệt cao được gọi là polyphenol, dâu tây là một loại thực phẩm không chứa natri, không chất béo, không cholesterol, ít calo. Chúng là một trong số 20 loại trái cây hàng đầu có khả năng chống oxy hóa và là một nguồn mangan và kali tốt.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>59,
                'name'=>'Mơ',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>32000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin A, Vitamin C và Vitamin E',
                'nutrient'=>'Polyphenol, Flavonoid, Calo, Carb, Chất đạm, Chất béo, Chất xơ, Kali,...',
                'thumbnail'=>'https://cdn.tgdd.vn/2021/03/content/4-800x450-10.jpg',
                'description'=>'Quả mơ chứa nguồn chất xơ tự nhiên hỗ trợ tiêu hóa, vitamin B5 thúc đẩy quá trình trao đổi chất trong cơ thể, vitamin E tốt cho da',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>60,
                'name'=>'Măng Cụt',
                'gardenName'=>'Nhà Vườn Duy Quang',
                'price'=>35000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin A, Vitamin C, Vitamin E,...',
                'nutrient'=>'Chất chống oxy hóa, Calo, Chất béo, Natri, Carbohydrate, Chất xơ, Chất đạm, Carbs,...',
                'thumbnail'=>'https://file.hstatic.net/1000377918/file/anh-trong-bai-viet_53b0060e71034684be74e4ee82f61d38.jpg',
                'description'=>'Mơ là một nguồn tuyệt vời có chứa nhiều chất chống oxy hóa, bao gồm beta carotene và vitamin A, vitamin C và vitamin E. Hơn nữa, chúng chứa nhiều chất chống oxy hóa polyphenol được gọi là flavonoid, đã được chứng minh là có khả năng bảo vệ chống lại bệnh tật, bao gồm cả bệnh tiểu đường và bệnh tim.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>61,
                'name'=>'Mãng Cầu Xiêm',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>18000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin B1, Vitamin B2,...',
                'nutrient'=>'Canxi, Kali, Sắt,...',
                'thumbnail'=>'https://cdn.tgdd.vn/2020/10/CookProductThumb/Untitled-1-620x620.jpg',
                'description'=>'Loại quả này rất hữu ích trong việc tăng cường hệ thống miễn dịch của cơ thể. Ăn mãng cầu sẽ làm giảm khả năng nhiễm trùng đồng thời cũng tiêu diệt các vi rút, vi khuẩn gây hại giúp cơ thể phòng ngừa các bệnh tốt hơn.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>62,
                'name'=>'Hồng',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>60000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin A, Vitamin C, Vitamin E, Vitamin B6, Vitamin B,...',
                'nutrient'=>'Chất xơ, Mangan, Đồng, Magiê, Kali, Phốt pho, Catechins, Gallocatechins, Betulinic acid, Carotenoid,...',
                'thumbnail'=>'https://vcdn-ngoisao.vnecdn.net/2017/10/28/DSC-8291-2468-1509189420.jpg',
                'description'=>'Hồng có hàm lượng natri thấp, rất tốt cho bệnh nhân cao huyết áp. Hồng cũng chứa nguồn vitamin C phong phú, có thể giúp tăng cường mức độ miễn dịch. Do đó, nó hoạt động như một lá chắn chống cảm lạnh, cúm, cũng như các bệnh nhiễm trùng phổi khác, bao gồm hen suyễn…',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>63,
                'name'=>'Hồng Xiêm',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>37000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin A, Vitamin C,...',
                'nutrient'=>'Năng lượng, Nước, Carbs, Chất đạm, Chất béo, Chất xơ,...',
                'thumbnail'=>'https://image-us.24h.com.vn/upload/1-2020/images/2020-03-21/1584766158-107-dung-mua-nhung-qua-hong-xiem-khi-thay-dau-hieu-nay-image1-1583979309-width600height450.jpg',
                'description'=>'Hồng xiêm đóng vai trò như một chất lợi tiểu, giúp loại bỏ được các độc tố ra khỏi cơ thể qua đường tiểu thường xuyên. Hàm lượng vitamin C dồi dào trong hồng xiêm giúp chống ho và cảm lạnh rất hiệu quả. Thường xuyên ăn hồng xiêm sẽ giúp bạn phòng chống và điều căn bệnh nhiễm trùng lạnh mãn tính.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>64,
                'name'=>'Cóc',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>25000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin B1, Vitamin A, Vitamin C,...',
                'nutrient'=>'Chất xơ, Glucid, Protein, Lipid, Cellulose, Tro, Acid,...',
                'thumbnail'=>'https://leep.imgix.net/2021/01/ckC6wN7K-qua-coc-va-vo-van-loi-ich-khong-phai-ai-cung-biet-01.png?auto=compress&fm=png&ixlib=php-1.2.1',
                'description'=>'Quả cóc cũng là món ăn quen thuộc của các chị em phụ nữ vì nó rất thơm, có vị chua, giòn khá dễ ăn. Theo Đông y, công dụng của quả cóc là thanh nhiệt, giải độc, giải khát, kiện tỳ vị. Quả cóc chứa nhiều acid ascorbic, trong 100g thịt cóc có tới 42g acid ascorbic có tác dụng tăng sức đề kháng cho những người bị cảm cúm.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>65,
                'name'=>'Mâm Xôi Đen',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>1000000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin K, Vitamin A,...',
                'nutrient'=>'Beta-carotene, Chất xơ, Axit ellagic,...',
                'thumbnail'=>'http://thichthucung.com/wp-content/uploads/cho-an-qua-mam-xoi.jpg',
                'description'=>'Mâm xôi đen chứa axit salicylic với đặc tính tương tự như aspirin(axit acetylsalicylic) giúp phòng chống bệnh tim, làm giảm hueets áp và giảm đau. Chống ung thư: Axit ellagic có tác dụng làm ngừng tăng trưởng các tế bào ung thư(đã được nghiên cứu tại phòng thí nghiệm).',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>66,
                'name'=>'Mâm Xôi Đỏ',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>400000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin K,...',
                'nutrient'=>'Calo, Carbs, Chất xơ, Protein, Chất béo, Mangan,...',
                'thumbnail'=>'https://thuthuatnhanh.com/wp-content/uploads/2021/07/hinh-anh-qua-mam-xoi-lam-nen.jpg',
                'description'=>'Mâm xôi đỏ có hàm lượng chất chống oxy hóa cao, có thể có tác dụng chống lại ung thư. Một số nghiên cứu trong phòng thí nghiệm cho thấy chiết xuất từ quả mọng - bao gồm cả quả mâm xôi đỏ - có khả năng ngăn chặn sự phát triển và tiêu diệt tế bào ung thư ruột kết, tuyến tiền liệt, vú và miệng.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>67,
                'name'=>'Mướp Đắng',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>180000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin A, Vitamin B9,...',
                'nutrient'=>'Năng lượng, Nước, Carbohydrate, Chất xơ, Sắt,...',
                'thumbnail'=>'https://cdn.tgdd.vn/2020/09/CookProduct/Tac-dung-cua-muop-dang-voi-suc-khoe-va-cac-luu-y-khi-dung-0-1200x676.jpg',
                'description'=>'Mướp đắng (còn gọi là khổ qua), thuộc họ bầu bí, là loại quả có hàm lượng vitamin C đứng hàng đầu trong các loại rau, dưa, bí',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>68,
                'name'=>'Quả Hạnh',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>400000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin E, Vitamin B2,...',
                'nutrient'=>'Chất xơ, Protein, Chất béo, Mangan, Magiê,...',
                'thumbnail'=>'https://trithucvn.org/wp-content/uploads/2017/12/hanh-nhan.jpg',
                'description'=>'Mướp đắng có công dụng phòng bệnh sốt xuất huyết, bảo vệ màng tế bào, phòng xơ vữa động mạch, kháng ung thư, nâng cao sức đề kháng, phòng cảm mạo, bảo vệ tim. Ngoài ra, chất glycoside của mướp đắng còn có tác dụng giảm đường trong máu nên có tác dụng trị liệu bổ trợ đối với bệnh đái tháo đường.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>69,
                'name'=>'Rau Ngót',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>19000,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin C, Vitamin A, Vitamin C,...',
                'nutrient'=>'Canxi, Sắt, Magiê, Mangan, Phospho, Kali, Natri, Kẽm, Đồng,...',
                'thumbnail'=>'https://khuyennongtphcm.com/wp-content/uploads/2020/08/rau-ngot.jpg',
                'description'=>'Rau ngót có tính mát, vị ngọt, có tác dụng thanh nhiệt, giải độc, lợi tiểu, giúp hạ sốt, tăng tiết nước bọt,… Hạ huyết áp: Trong rau ngót có chứa papaverin, chất này có tác dụng gây dãn mạch, chống co thắt cơ trơn. Vì vậy có tác dụng giảm huyết áp hữu hiệu.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>70,
                'name'=>'Mướp Rừng',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>25000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin E,...',
                'nutrient'=>'Calo, Carbonhydrate, Chất xơ, Kali, Kẽm, Sắt,...',
                'thumbnail'=>'https://media.ex-cdn.com/EXP/media.giadinhmoi.vn/files/content/2019/11/18/lac-le-giadinhmoi-1052.jpg',
                'description'=>'Mướp rừng chứa nhiều chất chống oxy hóa, tăng cường khả năng miễn dịch của bạn, bảo vệ cơ thể khỏi các gốc tự do có hại và ngăn chặn sự đột biến của tế bào dẫn đến ung thư. Ăn lặc lày được cho là làm giảm nguy cơ phát triển bệnh ung thư phổi, ung thư ruột kết và ung thư khoang miệng.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>71,
                'name'=>'Vải Thiều',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>30000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin E, Vitamin K, Vitamin B6,...',
                'nutrient'=>'Calo, Carbs, Chất đạm, Đường, Chất béo, Chất xơ,...',
                'thumbnail'=>'https://trithucvn.org/wp-content/uploads/2020/06/vai-thieu-1-3.jpg',
                'description'=>'Quả vải thiều là một trong những loại trái cây được ưa chuộng tiêu thụ nhiều vào dịp hè. Loại quả nhiệt đới này không chỉ giàu giá trị dinh dưỡng mà còn đem lại rất nhiều lợi ích ấn tượng đối với sức khoẻ, chẳng hạn như chữa lành các tổn thương, ngăn ngừa ung thư, tốt cho da và hệ tiêu hoá.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>72,
                'name'=>'Lê',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>100000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin B, Vitamin B2, Vitamin B3, Vitamin B6, Vitamin C, Vitamin K, Vitamin B9,...',
                'nutrient'=>'Canxi, Magie, Đồng, Mangan,...',
                'thumbnail'=>'https://comchaychabong.net/wp-content/uploads/2021/04/1619808900_202_Cac-loai-le-cach-chon-le-ngon-qua-le-bao.jpg',
                'description'=>'Lê là một loại trái cây chứa nhiều chất dinh dưỡng rất có lợi đối với sức khỏe như: Vitamin C, vitamin K, kali, chất đạm, carbs,... Hơn thế, lê còn cung cấp một lượng folate, provitamin A và niacin rất quan trọng đối với chức năng tế bào và sản xuất năng lượng, hỗ trợ sức khỏe cho làn da và chữa lành vết thương.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>73,
                'name'=>'Củ Cải',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>20000,
                'weight'=>'1 kg',
                'category'=>2,
                'vitamin'=>'Vitamin C, Vitamin B9, Vitamin A, Vitamin B, Vitamin B9,...',
                'nutrient'=>'Calo, Carbs, Protein, Chất xơ, Canxi, Magiê, Kali, Đồng,...',
                'thumbnail'=>'http://phunuvietnam.mediacdn.vn/media/news/13c5dfa246046c0beea97e100f32a1a9/cu-cai-8.jpg',
                'description'=>'Củ cải có chứa các hoạt tính sinh học betain, hỗ trợ chức năng gan khỏe mạnh. Khi gan hoạt động tốt, chất béo được chia nhỏ một cách hiệu quả, giúp giảm cân và ngăn ngừa mệt mỏi và buồn nôn. Betaine, một dưỡng chất được tìm thấy trong củ cải đường giúp làm giảm homocysteine huyết tương.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>74,
                'name'=>'Táo Mỹ',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>90000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin A, Vitamin E, Vitamin B1, Vitamin B2, Vitamin B6,...',
                'nutrient'=>'Calo, Nước, Protein, Carbs, Đường, Chất xơ, Chất béo,...',
                'thumbnail'=>'https://tieudung.vn/upload_images/images/2020/05/20/anhdaidien.jpg',
                'description'=>'Loại quả này giúp hỗ trợ giảm cân do hàm lượng chất xơ trong táo thúc đẩy cảm giác no, giảm lượng calo và tăng giảm cân. - Ăn nhiều táo giúp tăng mật độ khoáng xương, giảm nguy cơ loãng xương; Giảm nguy cơ mắc bệnh hen suyễn; Ngăn ngừa suy giảm tinh thần và làm chậm các dấu hiệu lão hóa. - Giảm nguy cơ mắc bệnh tiểu đường.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>75,
                'name'=>'Táo Việt Nam',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>35000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin A, Vitamin C, Vitamin P,...',
                'nutrient'=>'Axit chlorogenic, Axit oxalic, Carotene, Kali,...',
                'thumbnail'=>'https://cdn.tgdd.vn/Files/2020/04/07/1247398/tao-ta-va-tao-tay-co-nhung-tac-dung-chua-benh-gi--2.jpg',
                'description'=>'Loại quả này chứa nhiều vitamin A, C và carotene, kali, giúp củng cố hệ miễn dịch của cơ thể. Do đó, ăn nhiều loại táo này có thể giúp bạn tránh bị cảm lạnh và ho. Nhờ chất nhầy của loại trái cây này, nó cũng được coi là thuốc thảo dược để điều trị những cơn đau họng.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>76,
                'name'=>'Lựu',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>349000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin A, Vitamin C, Vitamin E, Vitamin K, Vitamin B19,...',
                'nutrient'=>'Chất xơ, Protein, Kali, Punicalagins, Axit Punici,...',
                'thumbnail'=>'https://hoaquafuji.com/storage/app/media/uploaded-files/an-luu-co-tac-dung-gi-fuji-4.jpg',
                'description'=>'Viêm mãn tính là một trong những yếu tố nguy cơ hàng đầu của nhiều bệnh nghiêm trọng, bao gồm bệnh tim mạch, ung thư, tiểu đường type 2, bệnh Alzheimer và béo phì. Lựu có đặc tính chống viêm mạnh, phần lớn cơ chế trung gian bởi các đặc tính chống oxy hóa của punicalagins.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>77,
                'name'=>'Gừng',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>60000,
                'weight'=>'1 kg',
                'category'=>2,
                'vitamin'=>'Vitamin C, Vitamin B1, Vitamin B2, Vitamin B6,...',
                'nutrient'=>'Calo, Carbohydrate, Protein , Chất béo, Chất xơ, Kali, Đồng, Mangan,...',
                'thumbnail'=>'https://cdn.tgdd.vn/Files/2020/05/19/1256662/tac-dung-cua-gung-va-nhung-mon-tu-gung.jpg',
                'description'=>'Gừng vừa được dùng để làm gia vị, vừa được dùng để làm thuốc vì sở hữu nhiều đặc tính dược phẩm tốt',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>78,
                'name'=>'Dưa Hấu',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>16800,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin A, Vitamin C, Vitamin B5,...',
                'nutrient'=>'Calo, Nước, Protein, Carbs, Đường, Chất xơ, Chất béo,...',
                'thumbnail'=>'https://danviet.mediacdn.vn/thumb_w/650/296231569849192448/2021/6/16/anh9-1623856207255743202804.jpg',
                'description'=>'Gừng có chứa chất gingerol có tính chống viêm. Bằng cách ức chế các chất chemokin, cytokin và các yếu tố gây viêm khác, gừng giúp cải thiện tình trạng viêm khớp gối và đau nhức liên quan. Thường xuyên sử dụng gừng có thể giúp ngăn ngừa sự khởi phát của bệnh xương khớp.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>79,
                'name'=>'Xoài',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>40000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin B5, Vitamin A, Vitamin C,...',
                'nutrient'=>'Potassium, Magiê, Đồng, Quercetin, Betacarotene và Astragalin,...',
                'thumbnail'=>'https://hongngochospital.vn/wp-content/uploads/2020/02/loi-ich-cua-xoai-4.jpg',
                'description'=>'Xoài chứa nhiều axit amin nên có ích cho những người làm việc bằng trí óc, suy nhược thần kinh. Xoài còn chữa thiếu máu, thiếu sắt ở phụ nữ. Xoài chín dù có vị ngọt nhưng lại chứa ít calo, giúp hạn chế thèm ăn, giảm lượng đường glucose và cholesterol trong máu, là thực phẩm được các bạn giảm cân yêu thích.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>80,
                'name'=>'Thanh Long Ruột Trắng',
                'gardenName'=>'Nhà Vườn Quang Huy',
                'price'=>15000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin A, Vitamin C,...',
                'nutrient'=>'Sắt, Canxi, Chất xơ và Ma-giê,...',
                'thumbnail'=>'https://giongcay.net/uploads/products/relative/636608613060180000.jpg',
                'description'=>'Quả thanh long chứa khoảng 60 calo/quả, giàu vitamin C, B1, B2 và B3, cùng với các khoáng chất như sắt, canxi và photpho. Trong 100g quả sẽ cung cấp khoảng 21 mg vitamin C, tương đương với 34% giá trị lượng vitamin C hằng ngày. Loại trái cây này có vị ngọt dịu, thơm mát nên từ lâu đã được nhiều người ưa chuộng. Người dùng có thể ăn trực tiếp, làm sinh tố hay salad,… tùy vào từng mục đích sử dụng.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>81,
                'name'=>'Thanh Long Ruột Đỏ',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=>20000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin A, Vitamin C,...',
                'nutrient'=>'Cellulose, Pectin, Sắt, Canxi, Chất xơ và Ma-giê,...',
                'thumbnail'=>'https://giadinh.mediacdn.vn/2015/thanhlong-1435825834109.jpg',
                'description'=>'Thịt của quả thanh long đỏ giàu chất dinh dưỡng, giá trị chữa bệnh cao, có tác dụng hạ huyết áp, hạ lipid máu, giải độc , dưỡng phổi, dưỡng da, cải thiện thị lực, đồng thời cũng có tác dụng nhất định đối với bệnh táo bón, tiểu đường.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>82,
                'name'=>'Đu Đủ',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=>15000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin A, Vitamin B9,...',
                'nutrient'=>'Calo, Carbohydrate, Chất xơ, Protein và Kali,...',
                'thumbnail'=>'https://bazaarvietnam.vn/wp-content/uploads/2021/03/cong-dung-cua-qua-du-du_1528885103.jpg',
                'description'=>'Đu đủ giàu vitamin C, một loại vitamin cần thiết cho cơ thể giúp đẩy mạnh quá trình sản xuất các tế bào bạch cầu và kháng thể, tăng cường sức đề kháng. Một trong những lợi ích của đu đủ là cung cấp cho bạn các chất chống oxy hoá mạnh làm giảm đáng kể nguy cơ mắc bệnh ung thư.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>83,
                'name'=>'Bơ Sáp',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=>20000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin K, Vitamin B9, Vitamin C, Vitamin B5, Vitamin B6, Vitamin E,...',
                'nutrient'=>'Kali, Axit oleic, Chất xơ, Chất béo...',
                'thumbnail'=>'https://traicayvuongtron.vn/resources/uploads/kien_thuc_trai_cay/cac-loai-bo-sap/top-cac-loai-bo-sap-ngon-tai-viet-nam-ban-da-biet-4.jpg',
                'description'=>'Chứa hàm lượng lutein carotene cao, ăn trái bơ sáp sẽ giúp cơ thể giúp chống lại sự thoái hóa thành các vết đen, có khả năng cải thiện bệnh đục nhân mắt và một số bệnh về mắt khác.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>84,
                'name'=>'Chanh Leo',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=>15000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin B, Vitamin A,...',
                'nutrient'=>'Beta carotene, Polyphenol, Calo, Chất xơ, Sắt, Kali,...',
                'thumbnail'=>'https://traicayvuongtron.vn/resources/uploads/kien_thuc_trai_cay/chanh-day/uong-nuoc-ep-chanh-lep-the-nao-de-khong-tu-giet-minh-5.jpg',
                'description'=>'Chanh leo chứa nhiều vitamin A và C, sắt, kali và các thành phần dinh dưỡng khác cung cấp một lượng đa sinh tố rất tốt cho việc bồi bổ sức khỏe con người. Trong chanh leo có chứa nhiều loại đường đơn giúp tăng cường thể lực mà lại không gây hại đến đường huyết nên rất tốt cho bệnh nhân tiểu đường.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>85,
                'name'=>'Roi Đỏ',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=>68000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin A, Vitamin B,...',
                'nutrient'=>'Sắt, Canxi, Chất xơ, Protein, Ma-giê, Photpho, Kali, Natri, Lưu huỳnh,...',
                'thumbnail'=>'https://giadinh.mediacdn.vn/2020/2/15/photo-1-15817501952731596412876.jpg',
                'description'=>'Quả roi giúp bổ sung lượng lớn kali và nước giúp tăng cường sức mạnh của cơ bắp, giảm chuột rút do thiếu kali, natri và nước.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>86,
                'name'=>'Ổi',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=>10500,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin A, Vitamin C, Vitamin B9, Vitamin B3, Vitamin B6, Vitamin K... ',
                'nutrient'=>'Carotene , Lycopene, Folate, Kali, Canxi, Magiê, Phốt pho,...',
                'thumbnail'=>'https://www.thuocdantoc.org/wp-content/uploads/2019/11/cay-oi.jpg',
                'description'=>'Quả roi giàu chất xơ, giúp bảo vệ chống lại các vấn đề tiêu hóa phổ biến như tiêu chảy và đầy hơi, hơn hết còn giúp kiểm soát cân nặng. Ngăn ngừa chuột rút cơ bắp: Quả roi cũng sở hữu một lượng kali, giúp tăng cường sức mạnh của cơ bắp và giảm chuột rút cơ bắp.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>87,
                'name'=>'Mít',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=>30000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin A, vitamin C, Vitamin B1,...',
                'nutrient'=>'Canxi, kali, Sắt, Niacin, Magneisum,...',
                'thumbnail'=>'https://static.toiimg.com/photo/msid-68107293/68107293.jpg?1592581',
                'description'=>'Mít là nguồn bổ sung vitamin C, vitamin A làm tăng sức đề kháng của cơ thể, chống oxy hoá mạnh mẽ, giúp duy trì đủ độ ẩm giúp da hồng hào và hạn chế nếp nhăn. Mít chỉ làm bạn tăng cân chỉ khi bạn ăn quá nhiều. Nếu ăn với liều lượng hợp lý, mít có thể giúp bạn giảm cân và tốt cho sức khỏe.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>88,
                'name'=>'Ngô',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=>5500,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin C, Vitamin B1, Vitamin B9,...',
                'nutrient'=>'Chất đạm, Chất béo, Chất xơ, Magie, Kali,...',
                'thumbnail'=>'https://afamilycdn.com/zoom/640_400/150157425591193600/2020/6/23/photo-1592901570489-1592901570716581215762-31-0-616-936-crop-1592901987009137866755.jpeg',
                'description'=>'Ngô là nguồn thực phẩm giàu năng lượng và chất dinh dưỡng, bao gồm protein, vitamin B, vitamin C, và carbohydrate. Ngô chứa lượng lớn chất xơ, kali và các chất oxy hóa. 100 g ngô hạt cung cấp 342 calo cho cơ thể, do đó ngô được coi là một nguồn cung cấp năng lượng tuyệt vời cho cơ thể bạn.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>89,
                'name'=>'Dứa',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=>29000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin B9, Vitamin C, Vitamin K, Vitamin E, Vitamin A,...',
                'nutrient'=>'Chất xơ, Mangan, Magie, Kali, Chất béo,...',
                'thumbnail'=>'https://static.tuoitre.vn/tto/i/s626/2017/04/08/hinh-2-1491643785.jpg',
                'description'=>'Dứa giàu vitamin A, vitamin C, canxi, kali, và phốt pho. Trong khi giàu chất xơ và năng lượng, dứa lại ít chất béo và cholesterol nên bổ dưỡng tuyệt vời mà bạn nên thêm vào chế độ ăn uống để cải thiện và duy trì sức khỏe. Dứa có chứa mangan, một khoáng chất cần thiết cho cơ thể để xây dựng xương và mô liên kết.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>90,
                'name'=>'Hành Tây',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=>21800,
                'weight'=>'1 kg',
                'category'=>2,
                'vitamin'=>'Vitamin C, Vitamin B, Vitamin B9, Vitamin B6,...',
                'nutrient'=>'Calo, Nước, Protein, Carbs, Đường, Chất xơ, Chất béo,...',
                'thumbnail'=>'https://www.knorr.com/content/dam/unilever/knorr_world/vietnam/general_image/savoury/other_savoury/teaser_meo_voi_hanh_tay-1187771.jpg',
                'description'=>'Hành tây có một số lợi ích sức khỏe, chủ yếu là do hàm lượng chất chống oxy hóa cao và các hợp chất chứa lưu huỳnh. Ăn hành tây có tác dụng kháng viêm, đồng thời giảm nguy cơ ung thư, hạ lượng đường trong máu và cải thiện sức khỏe của xương.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>91,
                'name'=>'Cà Tím',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=>20000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin PP, Vitamin A, Vitamin B1, Vitamin B2,...',
                'nutrient'=>'Đạm, Tinh bột, Tro, Canxi, Kali, Sắt, Nước, Chất béo, Chất xơ, Cholesterol, Phốt pho, Natri, Carotin,...',
                'thumbnail'=>'https://vinmec-prod.s3.amazonaws.com/images/20201204_163347_582595_eggplant.max-1800x1800.jpg',
                'description'=>'Chất xơ, kali, vitamin C, vitamin B-6 và chất chống oxy hóa trong cà tím đều hỗ trợ sức khỏe tim mạch. Một đánh giá được công bố vào năm 2019 cho thấy ăn thực phẩm có chứa một số flavonoid, bao gồm cả anthocyanins, giúp giảm các dấu hiệu viêm làm tăng nguy cơ mắc bệnh tim.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>92,
                'name'=>'Kiwi Xanh',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=>130000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin E, Vitamin K và Vitamin B9,...',
                'nutrient'=>'Potassium, Chất chống oxy hóa, Chất xơ, Calo,...',
                'thumbnail'=>'http://media.cooky.vn/images/blog-2016/kiwixanh.jpg',
                'description'=>'Kiwi xanh chứa rất nhiều vitamin C được xem là dưỡng chất thiết yếu giúp cơ thể tăng cường hệ miễn dịch, chống stress, giúp vết thương mau lành, hấp thụ tốt chất sắt, cũng như làm giảm xuất hiện các triệu chứng của một số bệnh thường gặp như cảm cúm, cảm lạnh.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>93,
                'name'=>'Kiwi Vàng',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=>200000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin E, Vitamin C, Vitamin B9, Vitamin K...',
                'nutrient'=>'Chất chống oxi hóa, Kali, Chất xơ, Actinidin,...',
                'thumbnail'=>'https://hoaquafuji.com/storage/app/media/anh-sua/cropped-images/kiwi-vang-2-0-25-1280-1098-1623467192.jpeg',
                'description'=>'Với hàm lượng vitamin E sẵn có, kiwi vàng giúp da săn chắc, xóa mờ các nếp nhăn, hạn chế dấu hiệu lão hóa da. Lượng vitamin C của kiwi vàng có tác dụng giúp da mềm mại, giảm bớt tác hại của tia cực tím cho da. Đặc biệt hơn, kiwi vàng còn có AHA, giúp chống viêm, trị mụn, dưỡng ẩm…',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>94,
                'name'=>'Súp Lơ Xanh',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=> 45000,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin K, Vitamin B9, Vitamin C, Vitamin A, Vitamin E,...',
                'nutrient'=>'Canxi, Chất xơ, Mangan, Protein, Phytochemical, Carotenoid,...',
                'thumbnail'=>'https://khuyennongtphcm.com/wp-content/uploads/2020/09/sup-lo-xanh-1.jpg',
                'description'=>'Súp lơ giàu vitamin K, vitamin C, nhiều chất chống oxy hóa cùng axit béo omega-3 giúp động mạch, mạch máu không bị tích tụ mảng bám. Điều này làm giảm nguy cơ mắc bệnh cao huyết áp và kiểm soát nồng độ cholesterol trong cơ thể.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>95,
                'name'=>'Nho Đen Không Hạt',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=> 199000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin K, Vitamin B1, Vitamin A,...',
                'nutrient'=>'Calo, Carbohydrate, Protein, Chất béo, Chất xơ,...',
                'thumbnail'=>'https://cdn.tgdd.vn/Products/Images/7578/211617/bhx/nho-den-nhap-khau-my-tui-1kg-201909250903535677.JPG',
                'description'=>'Tác dụng của nho đen đối với sức khỏe là vô cùng lớn nhờ hàm lượng vitamin C cao cùng các loại vitamin, khoáng chất và hàm lượng flavonoid tăng cường hệ miễn dịch. Ngoài ra, trong nho đen có lượng đường và axit hữu cơ nên khi ăn sẽ giúp giảm các triệu chứng khó tiêu, táo bón và các vấn đề liên quan đến thận.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>96,
                'name'=>'Đậu Hà Lan',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=> 80000,
                'weight'=>'1 kg',
                'category'=>1,
                'vitamin'=>'Vitamin A, Vitamin K, Vitamin C,...',
                'nutrient'=>'Lutein, Sắc tố carotene, Chất chống ô xy hóa, Saponin, Kali ...',
                'thumbnail'=>'https://hatgiongtot.net/image/cache/catalog/Hat-giong-qua/hat-giong-dau-ha-lan-lay-hat-500x551.jpg',
                'description'=>'Đậu Hà Lan chứa các khoáng chất thiết yếu như kali và magiê giúp ngăn ngừa huyết áp cao, một yếu tố nguy cơ chính của bệnh tim. Ngoài ra, hàm lượng chất xơ cao trong đậu Hà Lan làm giảm cholesterol xấu, từ đó làm giảm nguy cơ mắc bệnh tim.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>97,
                'name'=>'Na',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=> 50000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin C, Vitamin B6,...',
                'nutrient'=>'Magiê, Sắt, Calo, Carbohydrate, Acetogenin,...',
                'thumbnail'=>'https://image-us.eva.vn/upload/3-2020/images/2020-08-25/1598350772-9d9b9b4490966ce8f8adb54e6cd1395b.jpg',
                'description'=>'Hàm lượng magiê và kali trong na có tác dụng bảo vệ hệ thống tim mạch, thư giãn cơ bắp và kiểm soát huyết áp ổn định. Niacin, vitamin B6 và chất xơ cũng có tác dụng ngăn ngừa các cơn đau tim, giảm lượng cholesterol xấu trong cơ thể. Na có thể cung cấp các dưỡng chất nhanh chóng chống lại kiệt sức và suy nhược.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>98,
                'name'=>'Cà Rốt',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=> 17000,
                'weight'=>'1 kg',
                'category'=>2,
                'vitamin'=>'Vitamin K1, Vitamin A, vitamin B6,...',
                'nutrient'=>'Beta carotene, Chất xơ, Kali, Chất chống oxy hóa,...',
                'thumbnail'=>'https://cdn.tgdd.vn/Files/2017/01/04/933983/cach-chon-mua-va-bao-quan-ca-rot-1_760x570.jpg',
                'description'=>'Chất xơ và chất chống oxy hóa trong cà rốt giúp cải thiện quá trình chuyển hóa glucose khi bệnh bệnh tiểu đường. Các bằng chứng nghiên cứu cho thấy, hàm lượng vitamin A, C, carotenoid, kali có trong cà rốt có tác dụng tuyệt vời trong việc kích thích tóc phát triển, hạn chế nguy cơ rụng tóc, hói đầu.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>99,
                'name'=>'Cà Chua',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=> 30000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin A, Vitamin C, Vitamin K, Vitamin B6, Vitamin B9, Vitamin B1,...',
                'nutrient'=>'Kali, Mangan, Magiê, Canxi, Phốt pho, Đồng, Chất xơ, Protein,...',
                'thumbnail'=>'https://media.cooky.vn/images/blog-2016/bi-quyet-di-cho-chon-ca-chua-an-toan-ma-cac-ba-noi-tro-khong-nen-bo-qua%201.jpg',
                'description'=>'Với thành phần giàu các hoạt chất chống oxy hóa mạnh, vitamin A, vitamin k, canxi…, Cà chua hỗ trợ tăng cường sức khỏe răng, xương, và da, hạn chế tối đa tổn hại từ tia cực tím, một trong những nguyên nhân gây ra các nếp nhăn cho làn da.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id'=>100,
                'name'=>'Cà Pháo',
                'gardenName'=>'Nhà Vườn Tiến Dũng',
                'price'=>40000,
                'weight'=>'1 kg',
                'category'=>3,
                'vitamin'=>'Vitamin A, Vitamin C, Vitamin B1, Vitamin B2, Vitamin PP,...',
                'nutrient'=>'Protein, Canxi, Sắt, Magiê, Phospho, Kali, Kẽm, Đồng, Selen,...',
                'thumbnail'=>'https://hatgiongphuongnam.com/asset/upload/image/hat-giong-ca-phao-tim-1.2_.JPG',
                'description'=>'Cà pháo vị ngọt, tính hàn, có tác dụng tán huyết, tiêu viêm, chỉ thống, nhuận tràng, lợi tiểu, trị thũng thấp độc, trừ hòn cục trong bụng, ho lao.Bên cạnh đó còn giúp cải thiện sức khỏe làn da, ngăn ngừa cholesterol cao, tăng cường hệ miễn dịch và bảo vệ hệ tiêu hóa,...',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
